import type { PilotCase } from "@/lib/capp/types"

export const PILOT_CASES: PilotCase[] = [
  {
    id: "BP-01",
    name: "定位底板 A",
    family: "base-plate",
    familyLabel: "底板类夹具",
    material: "45 钢",
    thicknessMm: 20,
    lotSize: 12,
    features: ["四周外形", "2 个基准面", "4-φ10H7 定位孔", "安装沉孔"],
    hasPrecisionHole: true,
    datumUncut: true,
    irregular: false,
    actualBlank: "板材",
    actualFixture: "通用装夹",
    note: "小批量、外形规矩，平口钳装夹即可。",
    actualRoute: [
      { seq: 1, name: "下料", content: "按外形放余量锯切板材", machine: "锯床" },
      { seq: 2, name: "铣基准", content: "先铣大面作后续基准", machine: "立铣" },
      { seq: 3, name: "铣外形", content: "铣四周至图纸尺寸", machine: "立铣" },
      { seq: 4, name: "钻孔", content: "钻 4-φ10 底孔及沉孔", machine: "钻床" },
      { seq: 5, name: "铰孔", content: "铰 φ10H7 定位孔", machine: "钻床" },
    ],
  },
  {
    id: "BP-02",
    name: "定位底板 B",
    family: "base-plate",
    familyLabel: "底板类夹具",
    material: "45 钢",
    thicknessMm: 25,
    lotSize: 8,
    features: ["矩形底板", "一侧台阶", "2-φ12H7", "螺纹孔 M8"],
    hasPrecisionHole: true,
    datumUncut: true,
    irregular: false,
    actualBlank: "板材",
    actualFixture: "通用装夹",
    note: "台阶面在基准铣完后加工，避免二次找正误差。",
    actualRoute: [
      { seq: 1, name: "下料", content: "板材下料，单边留 3 mm", machine: "锯床" },
      { seq: 2, name: "铣基准", content: "铣底面与相邻侧面", machine: "立铣" },
      { seq: 3, name: "铣台阶", content: "铣一侧台阶至尺寸", machine: "立铣" },
      { seq: 4, name: "钻孔攻丝", content: "钻铰 φ12H7，攻 M8", machine: "钻床" },
    ],
  },
  {
    id: "BP-03",
    name: "定位底板 C",
    family: "base-plate",
    familyLabel: "底板类夹具",
    material: "Q235",
    thicknessMm: 16,
    lotSize: 20,
    features: ["薄板", "腰形槽", "通孔 φ8"],
    hasPrecisionHole: false,
    datumUncut: true,
    irregular: false,
    actualBlank: "板材",
    actualFixture: "通用装夹",
    note: "无配合孔，钻孔后去毛刺即可。",
    actualRoute: [
      { seq: 1, name: "下料", content: "剪板或锯切", machine: "锯床" },
      { seq: 2, name: "铣基准", content: "铣两大面保证平行", machine: "立铣" },
      { seq: 3, name: "铣槽钻孔", content: "铣腰槽，钻 φ8 通孔", machine: "立铣" },
    ],
  },
  {
    id: "BP-04",
    name: "定位底板 D",
    family: "base-plate",
    familyLabel: "底板类夹具",
    material: "45 钢",
    thicknessMm: 40,
    lotSize: 6,
    features: ["厚底板", "型腔", "4-φ16H7"],
    hasPrecisionHole: true,
    datumUncut: true,
    irregular: false,
    actualBlank: "块料",
    actualFixture: "通用装夹",
    note: "厚度超过板材常用规格，改用块料。",
    actualRoute: [
      { seq: 1, name: "下料", content: "块料锯切，六面留余量", machine: "锯床" },
      { seq: 2, name: "铣六面", content: "先铣基准再铣其余面", machine: "立铣" },
      { seq: 3, name: "铣型腔", content: "粗精铣型腔", machine: "立铣" },
      { seq: 4, name: "钻铰孔", content: "钻—扩—铰 φ16H7", machine: "钻床" },
    ],
  },
  {
    id: "BP-05",
    name: "定位底板 E",
    family: "base-plate",
    familyLabel: "底板类夹具",
    material: "45 钢",
    thicknessMm: 22,
    lotSize: 80,
    features: ["批量底板", "统一孔系", "外形一致"],
    hasPrecisionHole: true,
    datumUncut: true,
    irregular: false,
    actualBlank: "板材",
    actualFixture: "专用夹具",
    note: "批量到 80 件，做钻孔钻模，减少找正时间。",
    actualRoute: [
      { seq: 1, name: "下料", content: "板材批量下料", machine: "锯床" },
      { seq: 2, name: "铣基准外形", content: "铣基准与四周", machine: "立铣" },
      { seq: 3, name: "钻铰孔", content: "在钻模上钻铰定位孔", machine: "钻床" },
    ],
  },
  {
    id: "CP-01",
    name: "压板 A",
    family: "clamp-plate",
    familyLabel: "压板类夹具",
    material: "45 钢",
    thicknessMm: 18,
    lotSize: 15,
    features: ["腰形压紧槽", "压紧斜面", "通孔"],
    hasPrecisionHole: false,
    datumUncut: true,
    irregular: false,
    actualBlank: "板材",
    actualFixture: "通用装夹",
    note: "典型压板，先保证底面再铣槽。",
    actualRoute: [
      { seq: 1, name: "下料", content: "板材下料", machine: "锯床" },
      { seq: 2, name: "铣基准", content: "铣底面与侧面", machine: "立铣" },
      { seq: 3, name: "铣槽", content: "铣腰形压紧槽", machine: "立铣" },
      { seq: 4, name: "铣斜面", content: "铣压紧斜面", machine: "立铣" },
    ],
  },
  {
    id: "CP-02",
    name: "压板 B",
    family: "clamp-plate",
    familyLabel: "压板类夹具",
    material: "45 钢",
    thicknessMm: 16,
    lotSize: 10,
    features: ["U 形开口", "铰制孔 φ10H8"],
    hasPrecisionHole: true,
    datumUncut: true,
    irregular: false,
    actualBlank: "板材",
    actualFixture: "通用装夹",
    note: "开口与孔有位置关系，先孔后开口。",
    actualRoute: [
      { seq: 1, name: "下料", content: "板材下料", machine: "锯床" },
      { seq: 2, name: "铣基准", content: "铣两大面", machine: "立铣" },
      { seq: 3, name: "钻铰孔", content: "钻铰 φ10H8", machine: "钻床" },
      { seq: 4, name: "铣开口", content: "铣 U 形开口", machine: "立铣" },
    ],
  },
  {
    id: "CP-03",
    name: "压板 C",
    family: "clamp-plate",
    familyLabel: "压板类夹具",
    material: "45 钢",
    thicknessMm: 20,
    lotSize: 9,
    features: ["弯头压板", "弧形头", "腰槽"],
    hasPrecisionHole: false,
    datumUncut: true,
    irregular: true,
    actualBlank: "板材",
    actualFixture: "专用夹具",
    note: "外形不规则，通用钳口不好定位，用简易靠形块。",
    actualRoute: [
      { seq: 1, name: "下料", content: "按展开外形下料", machine: "锯床" },
      { seq: 2, name: "铣基准", content: "铣底面", machine: "立铣" },
      { seq: 3, name: "靠形铣外形", content: "在靠形块上铣弧形头", machine: "立铣" },
      { seq: 4, name: "铣腰槽", content: "铣压紧腰槽", machine: "立铣" },
    ],
  },
  {
    id: "CP-04",
    name: "压板 D",
    family: "clamp-plate",
    familyLabel: "压板类夹具",
    material: "40Cr",
    thicknessMm: 28,
    lotSize: 6,
    features: ["厚压板", "台阶", "螺纹孔"],
    hasPrecisionHole: false,
    datumUncut: true,
    irregular: false,
    actualBlank: "块料",
    actualFixture: "通用装夹",
    note: "较厚，板材规格不够，用块料。",
    actualRoute: [
      { seq: 1, name: "下料", content: "块料下料", machine: "锯床" },
      { seq: 2, name: "铣基准", content: "铣底面与侧面", machine: "立铣" },
      { seq: 3, name: "铣台阶", content: "铣压紧台阶", machine: "立铣" },
      { seq: 4, name: "钻孔攻丝", content: "钻攻螺纹孔", machine: "钻床" },
    ],
  },
  {
    id: "CP-05",
    name: "压板 E",
    family: "clamp-plate",
    familyLabel: "压板类夹具",
    material: "45 钢",
    thicknessMm: 18,
    lotSize: 60,
    features: ["统一外形", "统一腰槽"],
    hasPrecisionHole: false,
    datumUncut: true,
    irregular: false,
    actualBlank: "板材",
    actualFixture: "专用夹具",
    note: "批量压板，做简易铣槽胎具。",
    actualRoute: [
      { seq: 1, name: "下料", content: "板材批量下料", machine: "锯床" },
      { seq: 2, name: "铣基准外形", content: "铣底面与外形", machine: "立铣" },
      { seq: 3, name: "铣槽", content: "在胎具上铣腰槽", machine: "立铣" },
    ],
  },
]
